package com.jack.hhitseat.bean;

public class Login {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.user_id
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.ip
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private String ip;
    

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.login_time
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private String loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.user_id
     *
     * @return the value of login.user_id
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.user_id
     *
     * @param userId the value for login.user_id
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.ip
     *
     * @return the value of login.ip
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.ip
     *
     * @param ip the value for login.ip
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.login_time
     *
     * @return the value of login.login_time
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public String getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.login_time
     *
     * @param loginTime the value for login.login_time
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime == null ? null : loginTime.trim();
    }
}