package com.jack.hhitseat.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.stu_num
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private String stuNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ip
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.seat
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private String seat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isDo
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private Integer isdo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.stu_num
     *
     * @return the value of user.stu_num
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public String getStuNum() {
        return stuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.stu_num
     *
     * @param stuNum the value for user.stu_num
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setStuNum(String stuNum) {
        this.stuNum = stuNum == null ? null : stuNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ip
     *
     * @return the value of user.ip
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ip
     *
     * @param ip the value for user.ip
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.seat
     *
     * @return the value of user.seat
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public String getSeat() {
        return seat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.seat
     *
     * @param seat the value for user.seat
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setSeat(String seat) {
        this.seat = seat == null ? null : seat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isDo
     *
     * @return the value of user.isDo
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public Integer getIsdo() {
        return isdo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isDo
     *
     * @param isdo the value for user.isDo
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setIsdo(Integer isdo) {
        this.isdo = isdo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbg.generated Wed Mar 27 10:15:22 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}